baseURL = 'https://B102.github.io/fengchenjian/'
languageCode = 'zh'
defaultContentLanguage= 'zh'
title = '簡'
theme = 'PaperMod'

[params.homeInfoParams]
Title = "杏紅月光下，凜耀碧藍間。"
Content = "墨黛雲霧裡，靜映琉璃天。"

[[menu.main]]
name = "歸檔"
url = "archives"
weight = 10


[[menu.main]]
name = "名字"
url = "about"
weight = 20

[params]
  # hide all text in the footer
  hideFooter = true
