name: Publish to GH Pages
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          submodules: true  # needed for themes like PaperMod

      - name: Checkout destination
        if: github.ref == 'refs/heads/main'
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: built-site

      - name: Setup Hugo (latest extended)
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true


      - name: Build
        run: hugo --minify

      - name: Deploy
        if: github.ref == 'refs/heads/main'
        run: |
          cp -R public/* "${GITHUB_WORKSPACE}/built-site/"
          cd "${GITHUB_WORKSPACE}/built-site"
          git add .
          git config user.name 'dhij'
          git config user.email 'davidhwang.ij@gmail.com'
          git commit -m 'Updated site' || echo "No changes to commit"
          git push
